server:
  port: 8766

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigate
  cloud:
    gateway:
      routes:
        - id: deptService
          uri: http://localhost:8000/
          predicates:
            - Path=/deptService/**
        - id: hrService
          uri: http://localhost:8100/
          predicates:
            - Path=/hrService/**
